---
title: "Example script"
output: 
  bookdown::html_document2:
    number_sections: false
    toc: true
    toc_float:
      toc_collapsed: true
    theme: united
vignette: >
  %\VignetteEncoding{UTF-8}
  %\VignetteIndexEntry{example-script}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  markdown: 
    wrap: 72
---

## Load data

```{r load}

# Clear environment
rm(list = ls())

# Load relevant libraries
library(modelLong)
library(dplyr)
library(ggplot2)

# Load example longitudinal data (must be of long format)
data <- read.csv("../data/ortho.csv")[-1]
data_labelled <- data

# Rename variables
data_labelled <- data %>% dplyr::rename("Distance" = distance, "Age" = age)

data_labelled[sample(nrow(data_labelled), 5),]
```

## Data Summary

Print a summary table of the orthodontist data.

```{r summary}
# Data summary, stratified by Sex
summary_res <- data_labelled[-1] %>%
  modelLong::summary(data = .,
                     group_var = "Sex",
                     type = list(Age ~ "continuous"))
summary_res$table1 
```

## Data Visualization

Plot repeated measures of adolescent tooth growth over time.

```{r plots}
# Create plot of repeated measures
plot_res <- modelLong::plot(
  data = data,
  outcome = "bweight",
  time = "mage",
  id = "mid",
  col_group = "Low weight")


ggplot(data = data,
       aes(x = age, y = distance)) +
  geom_line(aes(group = Subject), alpha = 0.4) +
  geom_point(data = data %>% group_by(age) %>% summarise(mean = mean(distance)),
             aes(x = age, y = mean), size = 3) + 
  xlab("Age (years)") + ylab("Distance (mm)") + theme_bw() + 
  scale_x_continuous(breaks = seq(8,18,2))

plot_res$data_plot
plot_res$acf_plot
```


